version: '3'
services:
  db:
    container_name: pygma-user-db
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: P9VsR89@c!b9hSE
      MYSQL_DATABASE: pygma_users
      MYSQL_USER: pygma_admin
      MYSQL_PASSWORD: P9VsR89@c!b9hSE
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - pygma-network

  app:
    container_name: pygma-user-service
    depends_on:
      - db
    build: .
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/pygma_users?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false&autoReconnect=true&useSSL=false"
      SPRING_DATASOURCE_USERNAME: "pygma_admin"
      SPRING_DATASOURCE_PASSWORD: "P9VsR89@c!b9hSE"
      SPRING_JPA_HIBERNATE_DDL-AUTO: "update"
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
    networks:
      - pygma-network

networks:
  pygma-network:
    external: true