logging.level.root: INFO

server:
  port: 8081

spring:
  application:
    name: applications-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:applications
    generate-unique-name: false
    name: applications
    username: h2
    password: h2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      leaseRenewalIntervalInSeconds: 60
      lease-expiration-duration-in-seconds: 60
    preferIpAddress: true
    registryFetchIntervalSeconds: 60
    fetchRegistry: true

