logging.level.root: INFO

server:
  port: 8084

spring:
  application:
    name: user-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/pygma_users?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: pygma_admin
    password: P9VsR89@c!b9hSE
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  sql:
    init:
      mode: always
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: hello@pygma.co
    password: jzveaawclbgzdskx
    port: '587'
  resourcesPath: 'C:/Users/iries/Documents/workspaces/GitHub/Pygma/Pygma-Frontend/public'
  imagesFolder: '/assets/user-pictures/'

eureka:
  client:
    serviceUrl:
      defaultZone: http://pygma-eureka-server:8761/eureka
    instance:
      leaseRenewalIntervalInSeconds: 5
      lease-expiration-duration-in-seconds: 5
    preferIpAddress: true
    registryFetchIntervalSeconds: 5
    fetchRegistry: true

jwt:
  secret: P9VsR89@c!b9hSE
  refreshSecret: ESh9b!c@98RsV9PR

messages:
  batchNumber: PY5