-- USER TABLE
CREATE TABLE USERS (
  ID CHAR(50) PRIMARY KEY,
  USERNAME VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  LASTNAME VARCHAR(100),
  EMAIL VARCHAR(100) NOT NULL,
  PHONE VARCHAR(20),
  UNIQUE (USERNAME),
  UNIQUE (EMAIL)
);

-- ROLE TABLE
CREATE TABLE ROLES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL
);

-- CREATE  USER_ROLES TABLE
CREATE TABLE USER_ROLES (
  USER_ID CHAR(50),
  ROLE_ID INT,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID),
  PRIMARY KEY (USER_ID, ROLE_ID)
);

-- INSERT ROLES
INSERT INTO ROLES (NAME) VALUES
  ('ROLE_ADMIN'),
  ('ROLE_USER');

-- INSERT USER
INSERT INTO USERS (ID, USERNAME, PASSWORD, NAME, LASTNAME, EMAIL, PHONE)
VALUES (
  'c592534f-0d71-4f2c-8d3c-fb0e08101e29',
  'david.gomelo',
  'password123',
  'David',
  'Ibarguen',
  'david.ibarguen@gmail.com',
  '1234567890'
);

--  ROLES TO USER
INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
SELECT 'c592534f-0d71-4f2c-8d3c-fb0e08101e29', ID
FROM ROLES
WHERE NAME IN ('ROLE_ADMIN', 'ROLE_USER');
